- id: '1584208204811'
  alias: Brightness down
  description: ''
  trigger:
  - entity_id: sensor.0xccccccfffee59767_action
    platform: state
    to: rotate_left
  condition: []
  action:
  - device_id: 48c955acfb3042bb88949960d48a8953
    domain: light
    entity_id: light.woonkamer_lampen
    type: brightness_decrease
- id: '1584208266714'
  alias: Brightness up
  description: ''
  trigger:
  - entity_id: sensor.0xccccccfffee59767_action
    platform: state
    to: rotate_right
  condition: []
  action:
  - device_id: 48c955acfb3042bb88949960d48a8953
    domain: light
    entity_id: light.woonkamer_lampen
    type: brightness_increase
