- platform: template
  sensors:
    gangkast_deur:
      friendly_name: 'Gangkast - Deur'
      device_class: door
      icon_template: >
        {% if is_state('binary_sensor.gangkast_deur','on') %} mdi:door-open
        {% else %} mdi:door-closed
        {% endif %}
      value_template: >-
          {{ is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control', '22') if states('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control') in ['22','23'] else states('binary_sensor.fibaro_system_fgdw002_door_opening_sensor_2_sensor') }}

    wasmachine_status:
      friendly_name: "Wasmachine - Status"
      icon_template: >
        {% if is_state('binary_sensor.wasmachine_status','on') %} mdi:washing-machine
        {% else %} mdi:washing-machine-off
        {% endif %}
      delay_on:
        minutes: 3
      delay_off:
        minutes: 3
      value_template: >-
        {{ states('sensor.fibaro_system_fgwpe_f_wall_plug_gen5_power')|float > 5 }}

    dishwasher_status:
      friendly_name: "Vaatwasser - Status"
      icon_template: >
        {% if is_state('binary_sensor.dishwasher_status','on') %} mdi:dishwasher
        {% else %} mdi:dishwasher-off
        {% endif %}
      delay_on:
        minutes: 2
      delay_off:
        minutes: 5
      value_template: >-
        {{ states('sensor.switch_vaatwasser_power')|float > 5 }}