- alias: Request cleaning when not home
  trigger:
    platform: state
    entity_id: group.someone_home
    from: home
    to: not_home
    for: "00:10:00"
  condition:
  - condition: state
    entity_id: vacuum.roomba
    state: 'off'
  action:
    service: notify.mobile_app_rick_iphone11 
    data:
      title: Niemand meer thuis
      message: Moet Consuela even stofzuigen?
      data:
        push:
          category: vacuum

- alias: Start cleaning
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: RUN_VACUUM
  condition:
  - condition: state
    entity_id: vacuum.roomba
    state: 'off'
  action:
  - service: vacuum.start_pause
    entity_id: vacuum.roomba
