---
- alias: Vaatwasser Ready
  trigger:
    platform: state
    entity_id: binary_sensor.dishwasher_status
    from: 'on'
    to: 'off'
  action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.dishwasher_done
      data_template:
        datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
    - service_template: >
        {{ states("sensor.nearest_iphone_notify") }}
      data:
        title: "Utilities"
        message: "Dishwasher is done 🍽🍳"

- alias: Vaatwasser Started
  trigger:
    platform: state
    entity_id: binary_sensor.dishwasher_status
    from: 'off'
    to: 'on'
  action:
    service: input_datetime.set_datetime
    entity_id: input_datetime.dishwasher_started
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"