- alias: Badkamer Ventilatie On
  trigger:
  - platform: state
    entity_id: sensor.button_badkamer_action
    to: 'hold'
  condition:
  - condition: numeric_state
    entity_id: light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level
    value_template: '{% if states.light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level.state == "on"  %}{{ states.light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level.attributes.brightness }}{% else %}0{% endif %}'
    below: 254
  action:
  - service: light.turn_on
    entity_id: light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level
    data:
      brightness: 255

- alias: Badkamer Ventilatie Off  
  trigger:
  - platform: state
    entity_id: sensor.button_badkamer_action
    to: 'hold'
  condition:
  - condition: numeric_state
    entity_id: light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level
    value_template: '{% if states.light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level.state == "on"  %}{{ states.light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level.attributes.brightness }}{% else %}0{% endif %}'
    above: 254
  action:
  - service: light.turn_on
    entity_id: light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level
    data:
      brightness: 75
