- platform:  history_stats
  name:      Vacuuming Time Today
  entity_id: vacuum.roomba
  state:     'on'
  type:      time
  start:     '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end:       '{{ now() }}'

- platform:  history_stats
  name:      Vacuuming Time Week
  entity_id: vacuum.roomba
  state:     'on'
  type:      time
  start:     '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end:       '{{ now() }}'