---
- platform: template
  fans:
    ventilatie:
      friendly_name: "Ventilatie"
      value_template: "{{ states('light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level') }}"
      speed_template: >
        {% if states.light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level.attributes.brightness|int >= 200 %}
          high
        {% elif states.light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level.attributes.brightness|int >= 140 %}
          medium
        {% else %}
          low
        {% endif %}
      turn_on:
        service: light.turn_on
        data_template:
          entity_id: light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level
      turn_off:
        service: light.turn_off
        data_template:
          entity_id: light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level
      set_speed:
        service: light.turn_on
        data_template:
          entity_id: light.qubino_goap_zmnhvdx_flush_dimmer_0_10v_level
          brightness: >
            {% if speed == 'high' %}
              255
            {% elif speed == 'medium' %}
              150
            {% elif speed == 'low' %}
              50
            {% endif %}
